"""Build configuration for standalone binary packaging.

Pure Python, no external dependencies. Generates PyInstaller spec files,
build scripts, and packaging instructions - never runs actual build tools.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

VALID_METHODS = ("pyinstaller", "nuitka", "shiv")


@dataclass
class PackagingConfig:
    """Configuration for standalone binary packaging."""

    method: str = "pyinstaller"
    entry_point: str = "evalyn_sdk.cli.main:main"
    output_name: str = "evalyn"
    one_file: bool = True

    def as_dict(self) -> dict[str, Any]:
        return {
            "method": self.method,
            "entry_point": self.entry_point,
            "output_name": self.output_name,
            "one_file": self.one_file,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PackagingConfig:
        return cls(
            method=data.get("method", "pyinstaller"),
            entry_point=data.get("entry_point", "evalyn_sdk.cli.main:main"),
            output_name=data.get("output_name", "evalyn"),
            one_file=data.get("one_file", True),
        )


def _parse_entry_point(entry_point: str) -> tuple[str, str]:
    """Parse 'module.path:function' into (module_path, function_name)."""
    if ":" not in entry_point:
        return entry_point, "main"
    module_path, func_name = entry_point.rsplit(":", 1)
    return module_path, func_name


def generate_pyinstaller_spec(config: PackagingConfig) -> str:
    """Generate a PyInstaller .spec file content.

    The spec file configures PyInstaller to produce either a one-file
    or one-directory bundle.
    """
    module_path, func_name = _parse_entry_point(config.entry_point)
    script_path = module_path.replace(".", "/") + ".py"

    spec = f"""# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for {config.output_name}
# Generated by evalyn binary_packaging module

block_cipher = None

a = Analysis(
    ['{script_path}'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['evalyn_sdk'],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    {'a.binaries, a.zipfiles, a.datas,' if config.one_file else ''}
    [],
    exclude_binaries={not config.one_file},
    name='{config.output_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
"""

    if not config.one_file:
        return spec + f"""
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    name='{config.output_name}',
)
"""
    return spec


def generate_build_script(config: PackagingConfig) -> str:
    """Generate a shell script for building the standalone binary."""
    module_path, func_name = _parse_entry_point(config.entry_point)
    script_path = module_path.replace(".", "/") + ".py"

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        f"# Build script for {config.output_name}",
        "# Generated by evalyn binary_packaging module",
        "",
    ]

    if config.method == "pyinstaller":
        onefile = "--onefile" if config.one_file else "--onedir"
        lines.extend(
            [
                "# Ensure pyinstaller is installed",
                "pip install pyinstaller",
                "",
                "# Build the binary",
                f"pyinstaller {onefile} \\",
                f"    --name {config.output_name} \\",
                "    --hidden-import evalyn_sdk \\",
                "    --clean \\",
                f"    {script_path}",
                "",
                f'echo "Build complete: dist/{config.output_name}"',
            ]
        )
    elif config.method == "nuitka":
        onefile = "--onefile" if config.one_file else "--standalone"
        lines.extend(
            [
                "# Ensure nuitka is installed",
                "pip install nuitka",
                "",
                "# Build the binary",
                f"python -m nuitka {onefile} \\",
                f"    --output-filename={config.output_name} \\",
                "    --include-package=evalyn_sdk \\",
                f"    {script_path}",
                "",
                f'echo "Build complete: {config.output_name}"',
            ]
        )
    elif config.method == "shiv":
        lines.extend(
            [
                "# Ensure shiv is installed",
                "pip install shiv",
                "",
                "# Build the zipapp",
                "shiv -c evalyn \\",
                f"    -o {config.output_name}.pyz \\",
                "    .",
                "",
                f'echo "Build complete: {config.output_name}.pyz"',
            ]
        )

    lines.append("")
    return "\n".join(lines)


def estimate_binary_size(config: PackagingConfig) -> str:
    """Return a rough human-readable estimate of the output binary size.

    These are approximate values based on typical Python packaging results.
    """
    if config.method == "pyinstaller":
        if config.one_file:
            return "~30MB for pyinstaller one-file"
        return "~50MB for pyinstaller one-directory (uncompressed)"
    if config.method == "nuitka":
        if config.one_file:
            return "~20MB for nuitka one-file"
        return "~35MB for nuitka standalone directory"
    if config.method == "shiv":
        return "~5MB for shiv zipapp (requires system Python)"
    return "unknown packaging method"


def validate_packaging_config(config: PackagingConfig) -> list[str]:
    """Return a list of validation errors for the given config.

    Returns an empty list if the config is valid.
    """
    errors: list[str] = []

    if config.method not in VALID_METHODS:
        errors.append(
            f"method must be one of {', '.join(VALID_METHODS)}, "
            f"got '{config.method}'"
        )

    if not config.entry_point:
        errors.append("entry_point must not be empty")
    elif ":" not in config.entry_point:
        errors.append(
            "entry_point must be in 'module.path:function' format"
        )

    if not config.output_name:
        errors.append("output_name must not be empty")

    if config.method == "shiv" and config.one_file is False:
        errors.append("shiv only supports single-file output (one_file=True)")

    return errors


def format_packaging_instructions(config: PackagingConfig) -> str:
    """Return human-readable build instructions for the given config."""
    module_path, func_name = _parse_entry_point(config.entry_point)

    lines = [
        f"Packaging Instructions ({config.method})",
        "=" * 40,
        "",
        f"Entry point: {config.entry_point}",
        f"Output name: {config.output_name}",
        f"Single file: {'yes' if config.one_file else 'no'}",
        f"Estimated size: {estimate_binary_size(config)}",
        "",
        "Prerequisites:",
    ]

    if config.method == "pyinstaller":
        lines.extend(
            [
                "  pip install pyinstaller",
                "",
                "Build command:",
            ]
        )
        onefile = "--onefile" if config.one_file else "--onedir"
        script_path = module_path.replace(".", "/") + ".py"
        lines.append(
            f"  pyinstaller {onefile} --name {config.output_name} {script_path}"
        )
    elif config.method == "nuitka":
        lines.extend(
            [
                "  pip install nuitka",
                "  (also requires a C compiler)",
                "",
                "Build command:",
            ]
        )
        onefile = "--onefile" if config.one_file else "--standalone"
        script_path = module_path.replace(".", "/") + ".py"
        lines.append(
            f"  python -m nuitka {onefile} "
            f"--output-filename={config.output_name} {script_path}"
        )
    elif config.method == "shiv":
        lines.extend(
            [
                "  pip install shiv",
                "",
                "Build command:",
                f"  shiv -c evalyn -o {config.output_name}.pyz .",
            ]
        )

    lines.extend(
        [
            "",
            "Output location:",
        ]
    )

    if config.method == "pyinstaller":
        lines.append(f"  dist/{config.output_name}")
    elif config.method == "nuitka":
        lines.append(f"  ./{config.output_name}")
    elif config.method == "shiv":
        lines.append(f"  ./{config.output_name}.pyz")

    return "\n".join(lines)
