"""Shell tab-completion script generation for evalyn CLI.

Generates bash, zsh, and fish completion scripts from a static command/flag
registry. No external dependencies - scripts are emitted as plain strings.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class CompletionConfig:
    """Configuration for shell completion generation."""

    shell: str  # "bash", "zsh", or "fish"
    commands: list[str] = field(default_factory=list)
    flags: dict[str, list[str]] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "shell": self.shell,
            "commands": list(self.commands),
            "flags": {k: list(v) for k, v in self.flags.items()},
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CompletionConfig:
        return cls(
            shell=data["shell"],
            commands=list(data.get("commands", [])),
            flags={k: list(v) for k, v in data.get("flags", {}).items()},
        )


# ---------------------------------------------------------------------------
# Known evalyn commands and flags
# ---------------------------------------------------------------------------

_EVALYN_COMMANDS: list[str] = [
    "analyze",
    "annotate",
    "annotation-stats",
    "build-dataset",
    "calibrate",
    "cluster-failures",
    "cluster-misalignments",
    "compare",
    "dashboard",
    "export",
    "export-for-annotation",
    "import-annotations",
    "init",
    "insights",
    "list-calibrations",
    "list-calls",
    "list-metrics",
    "list-runs",
    "one-click",
    "quickstart",
    "run-eval",
    "select-metrics",
    "show-call",
    "show-projects",
    "show-run",
    "show-trace",
    "simulate",
    "status",
    "suggest-metrics",
    "trend",
    "validate",
]

_EVALYN_FLAGS: dict[str, list[str]] = {
    "analyze": ["--dataset", "--run", "--format", "--output", "--verbose"],
    "annotate": ["--dataset", "--item", "--metric", "--score", "--note"],
    "build-dataset": ["--source", "--output", "--limit", "--filter"],
    "calibrate": ["--dataset", "--metric", "--optimizer", "--output"],
    "compare": ["--dataset", "--run", "--baseline", "--format", "--output"],
    "dashboard": ["--dataset", "--port", "--open", "--output"],
    "export": ["--dataset", "--run", "--format", "--output"],
    "import-annotations": ["--dataset", "--file", "--format"],
    "init": ["--template", "--force"],
    "insights": ["--dataset", "--run", "--format", "--output", "--verbose"],
    "list-calls": ["--project", "--limit", "--format"],
    "list-runs": ["--dataset", "--limit", "--format"],
    "one-click": ["--dataset", "--config", "--output"],
    "quickstart": ["--framework", "--output"],
    "run-eval": ["--dataset", "--config", "--metrics", "--output", "--parallel"],
    "select-metrics": ["--dataset", "--mode"],
    "show-call": ["--id", "--format"],
    "show-run": ["--id", "--format", "--verbose"],
    "show-trace": ["--id", "--format", "--depth"],
    "simulate": ["--config", "--output", "--count"],
    "status": ["--dataset", "--format"],
    "suggest-metrics": ["--dataset", "--mode"],
    "trend": ["--dataset", "--metric", "--format", "--output"],
    "validate": ["--dataset", "--strict"],
}


def get_evalyn_commands() -> list[str]:
    """Return the list of known evalyn CLI commands."""
    return list(_EVALYN_COMMANDS)


def get_evalyn_flags() -> dict[str, list[str]]:
    """Return per-command flag mappings."""
    return {k: list(v) for k, v in _EVALYN_FLAGS.items()}


# ---------------------------------------------------------------------------
# Bash completion
# ---------------------------------------------------------------------------


def generate_bash_completion(
    commands: list[str],
    flags: dict[str, list[str]],
    prog: str = "evalyn",
) -> str:
    """Generate a bash completion script using compgen/complete."""
    cmds_str = " ".join(commands)

    case_arms: list[str] = []
    for cmd in sorted(flags):
        flag_str = " ".join(flags[cmd])
        case_arms.append(
            f'        {cmd})\n'
            f'            COMPREPLY=( $(compgen -W "{flag_str}" -- "$cur") )\n'
            f'            return 0\n'
            f'            ;;'
        )
    case_block = "\n".join(case_arms)

    return (
        f'# Bash completion for {prog}\n'
        f'# Generated by evalyn shell_completion module\n'
        f'\n'
        f'_{prog}_completions() {{\n'
        f'    local cur prev commands\n'
        f'    cur="${{COMP_WORDS[COMP_CWORD]}}"\n'
        f'    prev="${{COMP_WORDS[COMP_CWORD-1]}}"\n'
        f'    commands="{cmds_str}"\n'
        f'\n'
        f'    if [[ $COMP_CWORD -eq 1 ]]; then\n'
        f'        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )\n'
        f'        return 0\n'
        f'    fi\n'
        f'\n'
        f'    case "$prev" in\n'
        f'{case_block}\n'
        f'    esac\n'
        f'\n'
        f'    return 0\n'
        f'}}\n'
        f'\n'
        f'complete -F _{prog}_completions {prog}\n'
    )


# ---------------------------------------------------------------------------
# Zsh completion
# ---------------------------------------------------------------------------


def generate_zsh_completion(
    commands: list[str],
    flags: dict[str, list[str]],
    prog: str = "evalyn",
) -> str:
    """Generate a zsh completion function (_evalyn)."""
    cmd_lines: list[str] = []
    for cmd in commands:
        cmd_lines.append(f"        '{cmd}:{cmd} command'")
    cmds_block = "\n".join(cmd_lines)

    case_arms: list[str] = []
    for cmd in sorted(flags):
        flag_items = " ".join(f"'{f}'" for f in flags[cmd])
        case_arms.append(
            f"        {cmd})\n"
            f"            _arguments {flag_items}\n"
            f"            ;;"
        )
    case_block = "\n".join(case_arms)

    return (
        f"#compdef {prog}\n"
        f"# Zsh completion for {prog}\n"
        f"# Generated by evalyn shell_completion module\n"
        f"\n"
        f"_{prog}() {{\n"
        f"    local -a commands\n"
        f"    commands=(\n"
        f"{cmds_block}\n"
        f"    )\n"
        f"\n"
        f"    _arguments '1:command:->cmds' '*::arg:->args'\n"
        f"\n"
        f"    case $state in\n"
        f"        cmds)\n"
        f"            _describe 'command' commands\n"
        f"            ;;\n"
        f"        args)\n"
        f"            case $words[1] in\n"
        f"{case_block}\n"
        f"            esac\n"
        f"            ;;\n"
        f"    esac\n"
        f"}}\n"
        f"\n"
        f"_{prog}\n"
    )


# ---------------------------------------------------------------------------
# Fish completion
# ---------------------------------------------------------------------------


def generate_fish_completion(
    commands: list[str],
    flags: dict[str, list[str]],
    prog: str = "evalyn",
) -> str:
    """Generate fish shell complete commands."""
    lines: list[str] = [
        f"# Fish completion for {prog}",
        "# Generated by evalyn shell_completion module",
        "",
    ]

    # Subcommand completions
    for cmd in commands:
        lines.append(
            f"complete -c {prog} -n '__fish_use_subcommand' "
            f"-a '{cmd}' -d '{cmd} command'"
        )

    lines.append("")

    # Flag completions per subcommand
    for cmd in sorted(flags):
        for flag in flags[cmd]:
            long_name = flag.lstrip("-")
            lines.append(
                f"complete -c {prog} -n '__fish_seen_subcommand_from {cmd}' "
                f"-l '{long_name}' -d '{long_name}'"
            )

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------


def generate_completion(config: CompletionConfig, prog: str = "evalyn") -> str:
    """Dispatch to the correct shell generator based on config.shell."""
    generators = {
        "bash": generate_bash_completion,
        "zsh": generate_zsh_completion,
        "fish": generate_fish_completion,
    }
    gen = generators.get(config.shell)
    if gen is None:
        raise ValueError(f"Unsupported shell: {config.shell!r}")
    return gen(config.commands, config.flags, prog)


# ---------------------------------------------------------------------------
# Install instructions
# ---------------------------------------------------------------------------


def format_install_instructions(shell: str, prog: str = "evalyn") -> str:
    """Return human-readable instructions for installing completion."""
    if shell == "bash":
        return (
            f"# Add to ~/.bashrc:\n"
            f"eval \"$({prog} completions bash)\"\n"
            f"\n"
            f"# Or save to a file:\n"
            f"{prog} completions bash > ~/.local/share/bash-completion/completions/{prog}"
        )
    if shell == "zsh":
        return (
            f"# Add to ~/.zshrc:\n"
            f"eval \"$({prog} completions zsh)\"\n"
            f"\n"
            f"# Or save to fpath:\n"
            f"{prog} completions zsh > ~/.zfunc/_{prog}\n"
            f"# Then add to .zshrc: fpath=(~/.zfunc $fpath); autoload -Uz compinit; compinit"
        )
    if shell == "fish":
        return (
            f"# Save to fish completions directory:\n"
            f"{prog} completions fish > ~/.config/fish/completions/{prog}.fish"
        )
    raise ValueError(f"Unsupported shell: {shell!r}")
