from __future__ import annotations

from typing import Iterable, List, Optional, Dict, Any, Protocol, runtime_checkable

from ..models import Annotation, EvalRun, FunctionCall


@runtime_checkable
class StorageBackend(Protocol):
    """Protocol for storage backends. Used for type hints only."""

    def store_call(self, call: FunctionCall) -> None: ...
    def get_call(self, call_id: str) -> Optional[FunctionCall]: ...
    def list_calls(self, limit: int = 100) -> List[FunctionCall]: ...
    def store_eval_run(self, run: EvalRun) -> None: ...
    def list_eval_runs(self, limit: int = 20) -> List[EvalRun]: ...
    def list_eval_runs_by_project(
        self, dataset_name: str, limit: int = 20
    ) -> List[EvalRun]: ...
    def get_eval_run(self, run_id: str) -> Optional[EvalRun]: ...
    def store_annotations(self, annotations: Iterable[Annotation]) -> None: ...
    def list_annotations(
        self, target_id: Optional[str] = None, limit: int = 100
    ) -> List[Annotation]: ...
    def list_spans(self, call_id: str) -> List[Dict[str, Any]]: ...
    def close(self) -> None: ...
