from __future__ import annotations

from collections.abc import Iterable
from typing import Any, Protocol, runtime_checkable

from ..models import Annotation, EvalRun, FunctionCall, SpanMetricLink


@runtime_checkable
class StorageBackend(Protocol):
    """Protocol for storage backends. Used for type hints only."""

    # Call management
    def store_call(self, call: FunctionCall) -> None: ...
    def get_call(self, call_id: str) -> FunctionCall | None: ...
    def list_calls(
        self, limit: int = 100, project: str | None = None,
        lightweight: bool = False,
    ) -> list[FunctionCall]: ...
    def delete_calls(self, call_ids: list[str]) -> int: ...
    def resolve_call_id(self, short_id: str) -> str | None: ...

    # Eval run management
    def store_eval_run(self, run: EvalRun) -> None: ...
    def list_eval_runs(self, limit: int = 20, lightweight: bool = False) -> list[EvalRun]: ...
    def list_eval_runs_by_project(
        self, dataset_name: str, limit: int = 20, lightweight: bool = False
    ) -> list[EvalRun]: ...
    def get_eval_run(self, run_id: str) -> EvalRun | None: ...
    def resolve_eval_run_id(self, short_id: str) -> str | None: ...

    # Metric results (relational storage)
    def batch_insert_metric_results(
        self, run_id: str, results: list, batch_size: int = 1000
    ) -> None: ...
    def load_metric_results(self, run_id: str) -> list: ...

    # Annotations
    def store_annotations(self, annotations: Iterable[Annotation]) -> None: ...
    def list_annotations(
        self, target_id: str | None = None, limit: int = 100
    ) -> list[Annotation]: ...

    # Spans
    def list_spans(self, call_id: str) -> list[dict[str, Any]]: ...

    # Span-metric attribution
    def store_span_metric_links(self, links: Iterable[SpanMetricLink]) -> None: ...
    def list_span_metric_links(
        self,
        run_id: str,
        span_id: str | None = None,
        metric_result_id: str | None = None,
    ) -> list[SpanMetricLink]: ...

    def close(self) -> None: ...
