from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional, Protocol, runtime_checkable

from ..models import Annotation, EvalRun, FunctionCall, SpanMetricLink


@runtime_checkable
class StorageBackend(Protocol):
    """Protocol for storage backends. Used for type hints only."""

    # Call management
    def store_call(self, call: FunctionCall) -> None: ...
    def get_call(self, call_id: str) -> Optional[FunctionCall]: ...
    def list_calls(
        self, limit: int = 100, project: Optional[str] = None,
        lightweight: bool = False,
    ) -> List[FunctionCall]: ...
    def delete_calls(self, call_ids: List[str]) -> int: ...
    def resolve_call_id(self, short_id: str) -> Optional[str]: ...

    # Eval run management
    def store_eval_run(self, run: EvalRun) -> None: ...
    def list_eval_runs(self, limit: int = 20, lightweight: bool = False) -> List[EvalRun]: ...
    def list_eval_runs_by_project(
        self, dataset_name: str, limit: int = 20, lightweight: bool = False
    ) -> List[EvalRun]: ...
    def get_eval_run(self, run_id: str) -> Optional[EvalRun]: ...
    def resolve_eval_run_id(self, short_id: str) -> Optional[str]: ...

    # Metric results (relational storage)
    def batch_insert_metric_results(
        self, run_id: str, results: List, batch_size: int = 1000
    ) -> None: ...
    def load_metric_results(self, run_id: str) -> List: ...

    # Annotations
    def store_annotations(self, annotations: Iterable[Annotation]) -> None: ...
    def list_annotations(
        self, target_id: Optional[str] = None, limit: int = 100
    ) -> List[Annotation]: ...

    # Spans
    def list_spans(self, call_id: str) -> List[Dict[str, Any]]: ...

    # Span-metric attribution
    def store_span_metric_links(self, links: Iterable[SpanMetricLink]) -> None: ...
    def list_span_metric_links(
        self,
        run_id: str,
        span_id: Optional[str] = None,
        metric_result_id: Optional[str] = None,
    ) -> List[SpanMetricLink]: ...

    def close(self) -> None: ...
